create_routing_scenario:
	consul config write mesh/scenarios/routing/superheroes.defaults.hcl
	consul config write mesh/scenarios/routing/vegetables.defaults.hcl
	consul config write mesh/scenarios/routing/vegetables.router.hcl
