#The reason for this file has to do with how docker-compose merge strategy works and incompatible networks and modes in this demo
version: "3.9"
services:
  prometheus:
    networks:
      - mesh
  vegetables:
    networks:
      - mesh
    ports:
      - 8080:8080
  superheroes:
    networks:
      - mesh
  database:
    networks:
      - mesh
  rabbitmq:
    networks:
      - mesh
  prometheus:
    networks:
      - observability
  grafana:
    networks:
      - observability
  jaeger-query:
    networks:
      - observability
  jaeger-collector:
    networks:
      - observability
      - mesh
  cassandra:
    networks:
      - observability
  cassandra-schema:
    network_mode: "service:cassandra"
  jaeger-agent-superheroes:
    network_mode: "service:superheroes"
  jaeger-agent-vegetables:
    network_mode: "service:vegetables"
  loki:
    networks:
      - observability
  fluent-bit:
    networks:
      - observability

networks:
  mesh:
  observability:
